### ISSUE TITLE
old ansible results in Unsupported parameters for (docker_network) module: ipam_config

### ISSUE THREAD

**Issue by tomvanoppens** [chadgeary/cloudblock#1]
**Unsupported parameters for (docker_network) module: ipam_config Supported parameters include** 
api_version, appends, cacert_path, cert_path, connected, debug, docker_host, driver, driver_options, filter_logger, force, ipam_driver, ipam_options, key_path, network_name, ssl_version, state, timeout, tls, tls_hostname, tls_verify"

ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]

**FIX**
use a later version of ansible

**Comment by chadgeary** [comment]
Hey @tomvanoppens which playbook or deployment method are you using?

**Comment by tomvanoppens** [comment]
standalone deployment

# Clone and change to directory
git clone https://github.com/chadgeary/cloudblock && cd cloudblock/playbooks/

# Run playbook (target is the localhost)
ansible-playbook cloudblock_amd64.yml --extra-vars 'docker_network=172.18.0.0 docker_gw=172.18.0.1 docker_doh=172.18.0.2 docker_pihole=172.18.0.3 docker_wireguard=172.18.0.4 wireguard_network=172.19.0.0 doh_provider=opendns dns_novpn=1 wireguard_peers=10'

# Locate configurations
ls -ltrh /opt/wireguard/peer1/

**Comment by chadgeary** [comment]
OK - I'm going to close this issue because it's related to an older version of Ansible. I'm checking out the other issue you opened.
