### ISSUE TITLE
Ubuntu 22 Support

### ISSUE THREAD

**Issue by Dviros** [chadgeary/cloudblock#105]
Hey Chad :)
I tried to upgrade to Ubuntu 22 in an Azure deployment and it completely broke down the os lol.
Seems that there are couple of things to address:
- docker gpg key needs to be saved as gpg instead of asc; that was the old convention afaik and according to their docs, gpg is the right way to go.
- pip installations are breaking os packages, hence when attempting to install with pip, a new flag should be added "break-system-packages", or else they should be installed via apt.

Thanks again!
D

**Comment by Dviros** [comment]
When running on 20.04 on a brand new Azure machine, I get the following error:
```
TASK [Docker apt repo] **************************************************************************************************************************************************************
task path: /opt/cloudblock/playbooks/cloudblock_azure.yml:36
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:GPG error: https://download.docker.com/linux/ubuntu jammy InRelease: Unknown error executing apt-key, E:The repository 'https://download.docker.com/linux/ubuntu jammy InRelease' is not signed."}
```


Seems like these are the correct permissions for the docker.asc key:
- `sudo chmod a+r /etc/apt/keyrings/docker.asc`
Spun up a new 20.04 machine based on the latest version mentioned in the Azure deployment file and it works.

**Comment by chadgeary** [comment]
fixed by: https://github.com/chadgeary/cloudblock/pull/107, thanks for calling it out as well
