### ISSUE TITLE
Error: Failed to read variables file

### ISSUE THREAD

**Issue by Fallout476** [chadgeary/cloudblock#17]
i am following your directions to the letter both on your YT vid and her on github to update my instance of your project on GCP. this is what I'm seeing:

PS C:\Users\XXX> wsl
XXX@Tower-PC:/mnt/c/Users/XXX$ cd ~/cloudblock/gcp/
XXX@Tower-PC:~/cloudblock/gcp$ git pull
Already up to date.
XXX@Tower-PC:~/cloudblock/gcp$ terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/google from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Using previously-installed hashicorp/google v3.51.0
- Using previously-installed hashicorp/random v3.0.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
XXX@Tower-PC:~/cloudblock/gcp$ terraform apply -var-file="pvars.tfvars"

Error: Failed to read variables file

Error while reading pvars.tfvars: open pvars.tfvars: permission denied.

**Comment by chadgeary** [comment]
See the readme note about permissions, it’s not in the video. CTRL+F chown
