### ISSUE TITLE
IP is leaked

### ISSUE THREAD

**Issue by rxng** [chadgeary/cloudblock#29]
I have set this up and deployed on lightsail. My client phone connects successfully via wireguard. However , my original IP is still being leaked rather than using the lightsail’s IP. I can’t figure out what’s wrong and why the IP leaking is happening? 

I have not changed anything on the instance since cloudblock after deployed.

**Comment by chadgeary** [comment]
hey @rxng - What value did you set for `vpn_traffic` [here](https://github.com/chadgeary/cloudblock/blob/master/lightsail/aws.tfvars#L23)? This setting configures the wireguard clients that are generated.

If you deployed with the value set to `dns` - only your DNS traffic is routed via wireguard VPN.

If you want to change the behavior to all traffic, open wireguard on your phone and edit the imported VPN profile. Set the allowed IPs field to `0.0.0.0/0`.

**Comment by rxng** [comment]
Thanks for the reply @chadgeary , I managed to fix it by changing the allowed IPs. 

I may change the vpn_traffic and redeploy rather than manually changing the allowed ips each time!

also wondered why create extra s3 resource if we can use the lightsail instance itself to host the files? As it would be an extra cost.

**Comment by chadgeary** [comment]
Glad it’s resolved ☀️

For S3 it’s a matter of low cost backup and convenience.

Along with the client configs, the pihole and wireguard data directories are stored here in the event the instance needs to be rebuilt or exported.
