### ISSUE TITLE
Another issue with Get ph_password from Azure Vault Secret - The error was: KeyError: 'credential'

### ISSUE THREAD

**Issue by NeckBeardPrince** [chadgeary/cloudblock#42]
TASK [Get ph_password from Azure Vault Secret] *********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'credential'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1644863984.6313643-27889-142727842169844/AnsiballZ_azure_rm_keyvaultsecret_info.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1644863984.6313643-27889-142727842169844/AnsiballZ_azure_rm_keyvaultsecret_info.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1644863984.6313643-27889-142727842169844/AnsiballZ_azure_rm_keyvaultsecret_info.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_info_payload_2q4sz8fg/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py\", line 430, in <module>\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_info_payload_2q4sz8fg/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py\", line 426, in main\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_info_payload_2q4sz8fg/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py\", line 239, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_info_payload_2q4sz8fg/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 464, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_info_payload_2q4sz8fg/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 1509, in __init__\nKeyError: 'credential'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by chadgeary** [comment]
There is an ansible-collections/azure ticket open - I did some testing and see the same thing. Nice reporting!

https://github.com/ansible-collections/azure/issues/757

**Comment by NeckBeardPrince** [comment]
> There is an ansible-collections/azure ticket open - I did some testing and see the same thing. Nice reporting!
> 
> [ansible-collections/azure#757](https://github.com/ansible-collections/azure/issues/757)

Instead of running --upgrade could we lock it at `1.10`?

**Comment by chadgeary** [comment]
That's fine with the caveat to add a reminder to update it later. The same thing essentially happens with the build of [cloudflared](https://github.com/chadgeary/cloudblock/blob/master/playbooks/cloudblock_amd64.yml#L128).

If I have time I will do it, or you/someone can create a merge request and I'll review/merge.

**Comment by NeckBeardPrince** [comment]
> That's fine with the caveat to add a reminder to update it later. The same thing essentially happens with the build of [cloudflared](https://github.com/chadgeary/cloudblock/blob/master/playbooks/cloudblock_amd64.yml#L128).
> 
> If I have time I will do it, or you/someone can create a merge request and I'll review/merge.

Been awhile since I've messed with python, and even longer since Ansible. I'm uncertain if we need to lock the ansible[azure] or the ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt file.

**Comment by chadgeary** [comment]
this should be sufficient if inserted just before [line 42 (here)](https://github.com/chadgeary/cloudblock/blob/master/azure/az-custom_data.tpl#L42):

```
# avoid 1.1.11 because msi authentication does not work https://github.com/ansible-collections/azure/issues/757
sed -i -e 's#azure-common==1.1.11#azure-common==1.1.10#' ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
```

**Comment by NeckBeardPrince** [comment]
> this should be sufficient if inserted just before [line 42 (here)](https://github.com/chadgeary/cloudblock/blob/master/azure/az-custom_data.tpl#L42):
> 
> ```
> # avoid 1.1.11 because msi authentication does not work https://github.com/ansible-collections/azure/issues/757
> sed -i -e 's#azure-common==1.1.11#azure-common==1.1.10#' ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
> ```

> this should be sufficient if inserted just before [line 42 (here)](https://github.com/chadgeary/cloudblock/blob/master/azure/az-custom_data.tpl#L42):
> 
> ```
> # avoid 1.1.11 because msi authentication does not work https://github.com/ansible-collections/azure/issues/757
> sed -i -e 's#azure-common==1.1.11#azure-common==1.1.10#' ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
> ```

Sadly, same error. But I can see I'm running `1.1.10`.
```
root@pihole-instance:~# pip3 list
Package                           Version
--------------------------------- -------------------
adal                              1.2.7
ansible                           4.10.0
ansible-core                      2.11.7
applicationinsights               0.11.10
argcomplete                       1.12.3
asn1crypto                        0.24.0
attrs                             17.4.0
Automat                           0.6.0
azure-cli-core                    2.26.1
azure-cli-telemetry               1.0.6
azure-common                      1.1.10
azure-core                        1.21.1
azure-graphrbac                   0.61.1
azure-identity                    1.7.0
azure-keyvault                    1.0.0a1
azure-mgmt-apimanagement          0.2.0
azure-mgmt-authorization          0.51.1
azure-mgmt-automation             0.1.1
azure-mgmt-batch                  5.0.1
azure-mgmt-cdn                    3.0.0
azure-mgmt-compute                10.0.0
azure-mgmt-containerinstance      1.4.0
azure-mgmt-containerregistry      2.0.0
azure-mgmt-containerservice       9.1.0
azure-mgmt-core                   1.2.0
azure-mgmt-cosmosdb               0.5.2
azure-mgmt-datalake-nspkg         2.0.0
azure-mgmt-datalake-store         0.5.0
azure-mgmt-devtestlabs            3.0.0
azure-mgmt-dns                    2.1.0
azure-mgmt-eventhub               2.0.0
azure-mgmt-hdinsight              0.1.0
azure-mgmt-iothub                 0.7.0
azure-mgmt-keyvault               1.1.0
azure-mgmt-loganalytics           1.0.0
azure-mgmt-managedservices        1.0.0
azure-mgmt-managementgroups       0.2.0
azure-mgmt-marketplaceordering    0.1.0
azure-mgmt-monitor                3.0.0
azure-mgmt-network                12.0.0
azure-mgmt-notificationhubs       2.0.0
azure-mgmt-nspkg                  2.0.0
azure-mgmt-privatedns             0.1.0
azure-mgmt-rdbms                  1.9.0
azure-mgmt-recoveryservices       0.4.0
azure-mgmt-recoveryservicesbackup 0.6.0
azure-mgmt-redis                  5.0.0
azure-mgmt-resource               10.2.0
azure-mgmt-search                 3.0.0
azure-mgmt-servicebus             0.5.3
azure-mgmt-sql                    0.10.0
azure-mgmt-storage                11.1.0
azure-mgmt-trafficmanager         0.50.0
azure-mgmt-web                    0.41.0
azure-nspkg                       2.0.0
azure-storage                     0.35.1
bcrypt                            3.2.0
blinker                           1.4
certifi                           2018.1.18
cffi                              1.15.0
chardet                           3.0.4
charset-normalizer                2.0.9
click                             6.7
cloud-init                        21.4
colorama                          0.4.4
command-not-found                 0.3
configobj                         5.0.6
constantly                        15.1.0
cryptography                      3.3.2
distro-info                       0.18ubuntu0.18.04.1
docker                            5.0.3
httplib2                          0.9.2
humanfriendly                     8.2
hyperlink                         17.3.1
idna                              2.6
importlib-metadata                4.8.3
incremental                       16.10.1
isodate                           0.6.1
Jinja2                            2.10
jmespath                          0.10.0
jsonpatch                         1.16
jsonpointer                       1.10
jsonschema                        2.6.0
keyring                           10.6.0
keyrings.alt                      3.0
knack                             0.8.2
language-selector                 0.1
MarkupSafe                        1.0
msal                              1.17.0
msal-extensions                   0.3.1
msrest                            0.6.21
msrestazure                       0.6.4
netifaces                         0.10.4
oauthlib                          3.1.1
packaging                         21.3
PAM                               0.4.2
paramiko                          2.9.1
pexpect                           4.2.1
pip                               21.3.1
pkginfo                           1.8.2
portalocker                       1.7.1
psutil                            5.9.0
pyasn1                            0.4.2
pyasn1-modules                    0.2.1
pycparser                         2.21
pycrypto                          2.6.1
Pygments                          2.10.0
PyGObject                         3.26.1
PyJWT                             2.3.0
PyNaCl                            1.4.0
pyOpenSSL                         17.5.0
pyparsing                         3.0.6
pyserial                          3.4
python-apt                        1.6.5+ubuntu0.7
python-dateutil                   2.8.2
python-debian                     0.1.32
pyxdg                             0.25
PyYAML                            3.12
requests                          2.25.1
requests-oauthlib                 1.3.0
requests-unixsocket               0.1.5
resolvelib                        0.5.4
SecretStorage                     2.3.1
service-identity                  16.0.0
setuptools                        39.0.1
six                               1.16.0
sos                               4.1
ssh-import-id                     5.7
systemd-python                    234
tabulate                          0.8.9
Twisted                           17.9.0
typing_extensions                 4.0.1
ubuntu-advantage-tools            27.6
ufw                               0.36
unattended-upgrades               0.1
urllib3                           1.26.8
WALinuxAgent                      2.2.45
websocket-client                  1.2.3
wheel                             0.30.0
xmltodict                         0.12.0
zipp                              3.6.0
zope.interface                    4.3.2
```

**Comment by NeckBeardPrince** [comment]
Ayeeeeeeee i wish they would fix this issue

**Comment by doodlemania2** [comment]
I think this is blocking me too - seems there was an update to the Ansible ticket. For me it's on the Terraform side though. Do they share a codebase or something (not too familiar with the difference between the two).

**Comment by chadgeary** [comment]
The azure collection on ansible galaxy has not been updated yet - it may
still be a few days:

https://galaxy.ansible.com/azure/azcollection

**Comment by chadgeary** [comment]
i've pinned to a working version for now: https://github.com/chadgeary/cloudblock/pull/47

**Comment by chadgeary** [comment]
https://github.com/ansible-collections/azure/issues/757 resolved
