### ISSUE TITLE
azurerm_key_vault_access_policy Error on new pull

### ISSUE THREAD

**Issue by doodlemania2** [chadgeary/cloudblock#48]
Did a pull thinking the new patch you did to pin a working version in the other issue would fix me up, but getting this error still:
azurerm_role_assignment.ph-instance-role-assignment: Refreshing state... [id=/subscriptions/...mysubid.../providers/Microsoft.Authorization/roleAssignments/6fe97f4d-fae9-a444-027d-6ad7d27021fe]
╷
│ Error: expected "object_id" to be a valid UUID, got 
│ 
│   with azurerm_key_vault_access_policy.ph-vault-disk-admin,
│   on az-encryption.tf line 24, in resource "azurerm_key_vault_access_policy" "ph-vault-disk-admin":
│   24:   object_id    = data.azurerm_client_config.ph-client-conf.object_id
│ 
╵
╷
│ Error: expected "object_id" to be a valid UUID, got 
│ 
│   with azurerm_key_vault_access_policy.ph-vault-storage-admin,
│   on az-encryption.tf line 71, in resource "azurerm_key_vault_access_policy" "ph-vault-storage-admin":
│   71:   object_id    = data.azurerm_client_config.ph-client-conf.object_id
│ 
╵
╷
│ Error: expected "object_id" to be a valid UUID, got 
│ 
│   with azurerm_key_vault_access_policy.ph-vault-secret-admin,
│   on az-encryption.tf line 118, in resource "azurerm_key_vault_access_policy" "ph-vault-secret-admin":
│  118:   object_id    = data.azurerm_client_config.ph-client-conf.object_id
│

**Comment by chadgeary** [comment]
That seems like a new error - haven't seen it before.

I suggest starting over from scratch - you may need to manually destroy the azure resource group.

**Comment by doodlemania2** [comment]
Okie dokie - is there a way to delete the stuff without losing all the settings and logs?

**Comment by chadgeary** [comment]
the pihole and wireguard container data is backed up to azure object storage (azure calls it blob) periodically. This can either be downloaded then uploaded to a new blob storage container for another cloudblock deployment, or if you have terraform re-create the virtual machine - the virtual machine will pull the last backup from object storage.
