### ISSUE TITLE
Can we get rid of apache?

### ISSUE THREAD

**Issue by Jenpatrick** [chadgeary/cloudblock#5]
Apache is... pretty gross.

Nginx is really the new (or moreso just more sane and more used) hotness as this point.
Most stuff I toss up inAWS via terraform or cloudformation is just all nginx now...  the tide is turning.  

I'm well versed enough in both, that I might be able to submit a PR to change the proxy and ssl config over for the aws stuff and ansible... to work with nginx... but it could be a few weeks, so if it slips, ping me...

Or even https://www.lighttpd.net/  but that's aging a lot...

**Comment by chadgeary** [comment]
I wouldn’t mind a different TLS proxy at all, and I’m on the look out for something that will run in a well maintained container, especially something that can proxy with self signed certificates out of the box (which is why I went with Apache2).

linuxserver.io has a few interesting options that didn’t appear to quite fit the bill (they’re maintaining the WireGuard container).

**Comment by gstrauss** [comment]
Peanut gallery: lighttpd is actively maintained (says a lighttpd developer, me), though it might not have the all of the features you need.  lighttpd 1.4.56 is scheduled to be released in the next couple weeks, including support for mbedTLS and wolfSSL, two TLS libraries aimed at embedded systems.  Neither Apache nor nginx have modules to use those libraries.

I took a brief look at the Apache config and it appears that lighttpd will be able to support cloudblock's use.

**Comment by chadgeary** [comment]
Hey @gstrauss - thanks for the heads up. Does the lighttpd team plan on maintaining a first party or trusted third party docker container? It would fit really well with this project if so.

For example - I'm looking at dnscrypt-proxy as an alternative to cloudflared to avoid building the cloudflared image. Most of the hardware these deployments run on is very lightweight.

**Comment by Jenpatrick** [comment]
I saw the last release on the lighttp page was in January, has it advanced since then?

Also re: dnscyrpt-proxy and cloud flare, why not give options for both?

**Comment by gstrauss** [comment]
> Does the lighttpd team plan on maintaining a first party or trusted third party docker container?

I'll look into it, but no promises.

> I saw the last release on the lighttp page was in January, has it advanced since then?

Quite a bit.  HTTP/2 support is new in lighttpd 1.4.56.

**Comment by Jenpatrick** [comment]
@gstrauss  very nice!  I mean still it says last update was in January..  I love lighttpd, but was concerned about a lack of dev. :-)
https://www.lighttpd.net/ 

(is the web page right?  I mean I should have checked your Ghub releases first. https://github.com/lighttpd/lighttpd1.4/releases) 

But, ideally, maybe we all could chip in to make options... one for light, one for nginx, and then we have the existing apache.  I'm not sure if that is what @chadgeary would want because it could complicate things... but I'm always a fan of less ram/cpu use or just options in general.  :-)  

Doing devops in aws and azure is my day job, and I totally look at things from the eye of costing less money.  (But I also love cool features!) so yea, it can be a trade-off.  :-) But options are good, to have less of a trade-off?
-Cheers.

**Comment by Jenpatrick** [comment]
Just to double check,,, per ansible info...  Apache is always (in arm or amd64) installing via apt as a systemd service, and not as a docker container?  Because that makes things easier...

https://github.com/chadgeary/cloudblock/blob/master/playbooks/cloudblock_amd64.yml#L8-L17

**Comment by chadgeary** [comment]
I've been testing containerization of the web proxy (and wrapping that up in a sane deployment method). I've tested successfully the OCI deployment using this method and will likely move forward with it. The self-signed certificate is still done via Ubuntu package [ssl-cert](https://packages.ubuntu.com/search?keywords=ssl-cert) and we now need two additional static configuration files (versus one). This is a decent compromise between architectural+code complexity.

I'm still open to using nginx or lighttpd, there's nothing _wrong_ with apache httpd though.

@Jenpatrick I'll look for a PR if you decide to dive into nginx.

@gstrauss I'll look for a first/trusted third-party docker container for lighttpd in the future!

Cheers
