### ISSUE TITLE
New/Same Issue with Azure Deployment

### ISSUE THREAD

**Issue by doodlemania2** [chadgeary/cloudblock#51]
Brand new checkout of master, dropped in my az.tfvars, terraform init, then terraform plan -var-file="az.tfvars" getting this error still:

derek@Azure:~/clouddrive/cloudblock/azure$ terraform plan -var-file="az.tfvars"
╷
│ Error: expected "object_id" to be a valid UUID, got
│
│   with azurerm_key_vault_access_policy.ph-vault-disk-admin,
│   on az-encryption.tf line 24, in resource "azurerm_key_vault_access_policy" "ph-vault-disk-admin":
│   24:   object_id    = data.azurerm_client_config.ph-client-conf.object_id
│
╵
╷
│ Error: expected "object_id" to be a valid UUID, got
│
│   with azurerm_key_vault_access_policy.ph-vault-storage-admin,
│   on az-encryption.tf line 71, in resource "azurerm_key_vault_access_policy" "ph-vault-storage-admin":
│   71:   object_id    = data.azurerm_client_config.ph-client-conf.object_id
│
╵
╷
│ Error: expected "object_id" to be a valid UUID, got
│
│   with azurerm_key_vault_access_policy.ph-vault-secret-admin,
│   on az-encryption.tf line 118, in resource "azurerm_key_vault_access_policy" "ph-vault-secret-admin":
│  118:   object_id    = data.azurerm_client_config.ph-client-conf.object_id

I even cleared the .terraform directory from my home drive. Now sure what else could be the culprit.

**Comment by chadgeary** [comment]
My terraform plan runs OK, assuming i ran terraform init on a fresh directory. Are you provider versions different?

```
chad@server1:~/git/cloudblock/azure$ terraform version
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

**Comment by doodlemania2** [comment]
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

I'm doing this from my Azure shell if that makes a difference (wouldn't think so). I even recreated my tfvars file from my old one making sure I wasn't messing anything up. There's no resource group in Azure that corresponds so, not sure why it's throwing these errors like something's already deployed.

**Comment by chadgeary** [comment]
It could be due to azure shell, i'm not familar with it. If you run `az account show` it should provide details that terraform will be using - this should match the details in `~/.azure/azureProfile.json` though you may have multiple profiles.

For context the error'd resources are access policies for encryption on the cloudblock disk, storage container, and secret. `data.azurerm_client_config.ph-client-conf.object_id` is the azure identity running terraform (you).

**Comment by doodlemania2** [comment]
Tried from home too. That must be it - my user account is a subscription owner/admin but for whatever reason, it doesn't have the ability to "query" for these things somehow. I deleted the old cloudblock-instance RG, so not sure where it's missing what it needs. Will try to dig into AAD permissions.

**Comment by doodlemania2** [comment]
Fixed via udpholepunch no!
