### ISSUE TITLE
Additional Feature Request: Enable clients / peers connected to the same wireugard server to ping / connect to each other

### ISSUE THREAD

**Issue by HappyShr00m** [chadgeary/cloudblock#6]
Hi Chad, 

Thanks for the awesome effort. One additional feature that would be great is if you can add the option to enable peers connected to the same WireGuard server to be able to send traffic between each other. 

One use case that I am currently facing is, setting up a FreePBX system, which is an IP phone system, such that connecting the whole system to the WireGuard server will enable the phones, FreePBX server and Trunks (Gateways / SIP devices) to communicate between each other remotely / securely without any restrictions as if they're installed locally on one network. 

Cheers,

**Comment by chadgeary** [comment]
Hey @HappyShr00m - I saw your comment on youtube as well.

This is a great idea (and to be completely transparent - I think some additional work on the docker networks needs to be done to ensure proper separation of services, but that's for another [related] topic.)

With that said, to answer your question (and help detail my concerns with my tangent above), there are no real restrictions for the peers until proper network segmentation is done - it's all confined to the peer configuration files that are generated (and editable).

Edit the 'Allowed IPs' conf in the peers file to either:

0.0.0.0/0 (all traffic would route through the wireguard VPN)

or

172.18.0.0/23 (peers can talk with each other in 172.19.0.0/24 and with the pihole in 172.18.0.0/24)

**Comment by chadgeary** [comment]
Added peers for vpn_traffic var in f8e2e4e3a6ad4b9b63e72b9c0626de8792ed3eb6

**Comment by HappyShr00m** [comment]
Awesome. Thank you so much
