### ISSUE TITLE
Upgrade to Python 3.8

### ISSUE THREAD

**Issue by dot-mike** [chadgeary/cloudblock#70]
Ansible 2.12 requires Python 3.8. When installing Ubuntu 18.04 the default Python version is 3.6 which is to old and deprecated (although ansible 2.11 is installed as of today, the user gets a deprecated warning).
By using deadsnakes PPA the system can be upgraded to a new Python version with 18.04 LTS.
 
 Ref. issues in #58

**Comment by chadgeary** [comment]
This should be fixed with [the bump to Ubuntu 22.04](https://github.com/chadgeary/cloudblock/commit/3be0dbceabcd99838e7d45830081ae7275862dbd) (20.04 for Lightsail)
