### ISSUE TITLE
systemd-resolve --status no longer exists in Ubuntu 22.04, replace w/ resolvectl

### ISSUE THREAD

**Issue by cronus42** [chadgeary/cloudblock#73]
https://github.com/chadgeary/cloudblock/blob/9dfea915a694a0292fd53cf2cc57e56da462050f/aws/aws-instance.tf#L26

  user_data = <<EOF
 #!/bin/bash
 # replace systemd-resolved with static dns derived from dhcp
-DNS_SERVER=$(systemd-resolve --status | awk -F': ' '/DNS Servers/{print $2}')
+DNS_SERVER=$(resolvectl | awk -F': ' '/DNS Servers/{print $2}')
 systemctl disable systemd-resolved
 systemctl stop systemd-resolved
 rm -f /etc/resolv.conf

**Comment by chadgeary** [comment]
thank you!

**Comment by chadgeary** [comment]
2194f0e
